### ISSUE TITLE
Fix click link treeview

### ISSUE THREAD

**Issue by coppo** [italia-it/ita-web-toolkit#10]
L'implementazione del menù offcanvas non propaga gli eventi sul click.
Risulta impossibile raggiungere qualsiasi link: cliccando indifferentemente su un nodo figlio o padre il menù si comporta nello stesso modo ed effettua il toggle dell'elemento.

**Comment by gunzip** [comment]
ok verifico. il problema non è dell'offcanvas di per sé, suppongo ti riferisca a questo componente:
https://italia-it.github.io/ita-web-toolkit/components/detail/treeview.html

tuttavia sarei per evitare i link sui livelli espandibili. ad esempio su http://www.comune.venezia.it/ cliccando su 'il comune' non si apre il sottomenu ma si va direttamente alla pagina; cliccando invece sulla "freccia" si espande il sottomenu (un comportamento controintuitivo). è lo stesso effetto che si ha su design.italia.it, tuttavia in questo secondo caso il menu rimane visibile (e con esso le voci espanse) mentre sul sito di venezia il menu torna nascosto e non i sottolivelli scompaiono.

**Comment by mirkobattisti** [comment]
Credo che la navigazione sia la parte più complessa di un sito web, e qui si sono aperte diverse questioni. Provo ad esprimere con ordine le mie opinioni.
Il menu off-canvas implementato nel toolkit lavora bene ma credo sia migliorabile per quanto riguarda i seguenti aspetti:
- il livello di profondità esplorabile da menu deve secondo me essere limitato, onde evitare che diventi davvero troppo lungo (anche se lo spazio è teoricamente infinito) - probabilmente questo si può tradurre in una raccomandazione.
- Quando ci sono molti menu aperti, la freccia 'su/giù' non aiuta a capire cosa è aperto e cosa è chiuso. Proporrei l'utilizzo di '+' e '-', come suggerito in questo articolo http://uxmovement.com/navigation/where-to-place-your-accordion-menu-icons/ - nello stesso articolo viene proposto di mettere l'icona sulla sinistra, ma su questo ho qualche riserva in più. In alternativa credo aiuterebbe un meccanismo che, quando si apre una voce di menu per esplorare i figli, chiudesse un eventuale altra voce aperta sullo stesso livello (in questo momento il menu ha questo comportamento solo al primo livello). In tal caso sono convinto che la freccia non risulterebbe più così fuorviante.
- lo schema colori del menu nell'off-canvas mi risulta incomprensibile. O meglio, è comprensibile solo dopo un confronto delle varie voci aperte/chiuse, ma è uno sforzo che l'utente non dovrebbe fare: secondo me meglio lasciare lo sfondo sempre uguale e demandare all'accoppiata "icona/spazio a sinistra" l'indicazione della struttura (che deve comunque essere limitata come numero di livelli).
- se una voce di menu ha dei figli, come raggiungo la pagina legata a quella voce? Sono d'accordo sulla soluzione indicata su www.funzionepubblica.gov.it, è pur vero che lì la struttura è semplice e ci sono 4 voci di menù che contengono figli, quindi il tutto è molto semplificato. Ancora una volta, il numero di livelli esplorabile da menu deve essere limitato.
- ricordo una implementazione leggermente diversa di menu, che era presente nella versione 4 (vado a memoria) del Framework Zurb Foundation. E' quella che viene chiamata "the ol' right-to-left" in questo articolo: http://bradfrost.com/blog/web/complex-navigation-patterns-for-responsive-design/ - Il menù "si sposta" di livello od ogni navigazione, restringendo il contesto ad ogni passo. Non è altro che il vecchio "drill down", che però risulta a mio avviso efficace su mobile.

Una volta limitato il numero di livelli esplorabile da menù, succede che a un certo punto la navigazione si sposta "nella pagina": come presentare la navigazione "di sezione" in una pagina che abbia ancora dei figli? Potrebbe essere con i "link in evidenza" mostrati qui https://italia-it.github.io/ita-web-toolkit/components/detail/page--default.html, anche se l'utente ci arriva solo dopo aver letto il testo di quella pagina.
Oppure l'idea era quella di utilizzare i link "correlati" sulla destra, come avviene qui http://www.funzionepubblica.gov.it/dipartimento-della-funzione-pubblica? (sulla destra c'è una sorta di menù dove vedo i figli della pagina). Non sono certo di essere d'accordo su questo: elementi correlati ed elementi figli sono due cose diverse a mio avviso, e andrebbero mantenuti separati. Certo che quell'elemento posizionato sulla destra e che somiglia molto a un menu risulta forse fuorviante.

Tutte queste considerazioni valgono in modo particolare per il comportamento del menu su mobile, perché su Desktop, posto che le voci di primo livello devono essere limitate, l'utilizzo del menu è a mio (e non solo) avviso, imbattibile: https://www.nngroup.com/articles/hamburger-menus/

Ah, ho già detto che il numero di livelli esplorabile da menu dovrebbe essere limitato?
