### ISSUE TITLE
Fix treeview: chiusura sottomenu al click

### ISSUE THREAD

**Issue by gunzip** [italia-it/ita-web-toolkit#14]
#11

> quando si apre una voce di menu per esplorare i figli, chiudere un'eventuale altra voce aperta sullo stesso livello (in questo momento il menu ha questo comportamento solo al primo livello).

**Comment by gunzip** [comment]
@mirkobattisti non mi è chiaro il task, ho verficato che quando un sottomenu viene espanso i sottomenu dello stesso livello vengono chiusi

**Comment by mirkobattisti** [comment]
@gunzip ho verificato e credo di aver preso un abbaglio quando ho segnalato la cosa, forse confuso dallo schema colori del menu che fatico a comprendere. Chiedo scusa.

**Comment by gunzip** [comment]
ho tolto i colori :)
