### ISSUE TITLE
paginazione

### ISSUE THREAD

**Issue by gunzip** [italia-it/ita-web-toolkit#22]

**Comment by gunzip** [comment]
https://www.stefanjudis.de/aria-selected-and-when-to-use-it.html

**Comment by AlessandroVecchi** [comment]
Questo componente è in fase di realizzazione?

**Comment by gunzip** [comment]
si a bassa priorità. non sarà molto diverso da http://v4-alpha.getbootstrap.com/components/pagination/

**Comment by AlessandroVecchi** [comment]
Alcuni script pensati per bootstrap ma usabili anche al di fuori:
https://esimakin.github.io/twbs-pagination/
http://botmonster.com/jquery-bootpag/
http://www.pontikis.net/labs/bs_pagination/
Da valutare se hanno i corretti requisiti.

**Comment by gunzip** [comment]
mi limiterei a dare un stile di base e poche indicazioni necessarie:
https://github.com/italia-it/ita-web-toolkit/blob/master/src/modules/pager/README.md

i fornitori valuteranno, a seconda della specifica esigenza, eventuali comportamenti dinamici e come implementarli.
