### ISSUE TITLE
L'installazione fallisce su ubuntu 16.10

### ISSUE THREAD

**Issue by tassoman** [italia-it/ita-web-toolkit#29]
> WARN engine @frctl/fractal@1.0.8: wanted: {"node":">= 4.4.7"} (current: {"node":"4.2.6","npm":"3.5.2"})
> npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

Mi sembra di capire che la versione di `node` e `npm` fornita con ubuntu 16.10 non sia adeguata, ci sono suggerimenti su come ottenere le versioni più recenti? Possibilmente traendo dai PPA, senza compilare.

> npm WARN optional Skipping failed optional dependency /@frctl/fractal/browser-sync/chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
> npm WARN optional Skipping failed optional dependency /@frctl/fractal/chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

**Comment by gunzip** [comment]
è possibile aggiornare nodejs all'ultima versione tramite l'utility `n`

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

dovrebbe funzionare con versioni di node >= 5.x

**Comment by tassoman** [comment]
Adesso ho node 7.0.0 ma sembra anche che debba procurarmi un machintosh...

> npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
> /usr/local/bin/fractal -> /usr/local/lib/node_modules/@frctl/fractal/bin/fractal
> /usr/local/lib
> └── @frctl/fractal@1.0.8 
> 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/@frctl/fractal/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/@frctl/fractal/node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
>

**Comment by gunzip** [comment]
io ho la seguente configurazione (funzionante):

Ubuntu 16.04.1
node v5.0.0
npm 3.4.0

provo con un upgrade a node 7.x

nell'output che riporti vedo solo dei warning (che si possono tranquillamente ignorare), puoi provare a far girare lo stesso `npm run watch` ?

**Comment by gunzip** [comment]
ho provato con node 7.x, mi da i warning, ma non causano nessun problema. posso chiudere la issue ?

**Comment by tassoman** [comment]
Ottimo grazie! :)
