### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by sebailfico** [italia-it/ita-web-toolkit#34]
Ciao,
ho seguito gli step classici nella vostra [documentazione ](https://italia-it.github.io/ita-web-toolkit/docs/sviluppare.html) cioè
`git clone https://github.com/italia-it/ita-web-toolkit`
`npm install`
ma allo step `npm run build` va in errore e mi dà gli errori

> npm ERR! Tell the author that this fails on your system:
npm ERR!     suitcss -m -c .postcss.js index.css build/build.css

e 

> npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all build:resources build:css build:js build:styleguide

In allegato il logfile
[npm-debug.zip](https://github.com/italia-it/ita-web-toolkit/files/654616/npm-debug.zip)

**Comment by gunzip** [comment]
subito dopo aver eseguito `npm install` puoi provare a eseguire

`node_modules/suitcss-preprocessor/bin/suitcss -m -c .postcss.js index.css build/build.css`

e riportare qui l'output del comando ?

non mi è chiaro però come il log che hai allegato si correla all'errore che segnali. la riga:

`26 error 404 'ita-web-toolkit' is not in the npm registry.`

sembrerebbe indicare che è stato eseguito un comando del tipo `npm install ita-web-toolkit` (è così ?)

**Comment by sebailfico** [comment]
L'output del comando è:
"node_modules\suitcss-preprocessor\bin\suitcss" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
Sono su Windows.

Riguardo all'errore 
`26 error 404 'ita-web-toolkit' is not in the npm registry.`
chiedo scusa, l'ho provocato io seguendo le istruzioni a terminale che suggerivano di lanciare:
`npm bugs ita-web-toolkit`
Sapevo non avrebbe funzionato ma ero curioso...

Grazie

**Comment by gunzip** [comment]
puoi verificare che il file `node_modules\suitcss-preprocessor\bin\suitcss` esista nella dir del toolkit ? 

dovrebbe averlo scaricato durante `npm install`.

**Comment by sebailfico** [comment]
Si, esiste

**Comment by gunzip** [comment]
puoi verificare lanciando:

`node node_modules/suitcss-preprocessor/bin/suitcss -m -c .postcss.js index.css build/build.css` ?

(ipotizzo che l'errore sia dovuto al fatto che node non sia nel path di sistema o al tipo di terminale utlizzato, controllo asap su windows)

**Comment by sebailfico** [comment]
> C:\Users\Seba\git\ita-web-toolkit>node node_modules\suitcss-preprocessor\bin\suitcss -m -c .postcss.js index.css build\build.css
>module.js:327
    throw err;
    ^
>Error: Cannot find module 'read-cache'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Seba\git\ita-web-toolkit\.postcss.js:1:81)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by gunzip** [comment]
è possibile che accada poiché manca read-cache nel package.json
`npm install --save-dev read-cache` prima di rilanciare il comando
potrebbe risolvere (puoi provare ?). nel mentre lo integro.

**Comment by sebailfico** [comment]
Eh, ci sarei dovuto arrivare, perdonami.
Ho installato il modulo, lanciato `npm run build` ma fallisce ancora, allego il logfile.
[npm-debug.zip](https://github.com/italia-it/ita-web-toolkit/files/655044/npm-debug.zip)

Se invece lancio il comando singolo di suitcss questo è l'output

> C:\Users\Seba\git\ita-web-toolkit>node node_modules\suitcss-preprocessor\bin\suitcss -m -c .postcss.js index.css build\b
> uild.css
> C:\Users\Seba\git\ita-web-toolkit\config.js:1
> (function (exports, require, module, __filename, __dirname) { let CONFIG = {}
>                                                               ^^^
> 
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (C:\Users\Seba\git\ita-web-toolkit\.postcss.js:2:16)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)

**Comment by gunzip** [comment]
aggiungi la riga `'use strict'` all'inizio del file `.postcss.js`

grazie a te per la pazienza, il debug aiuterà altri che potrebbero avere gli stessi problemi :)

**Comment by sebailfico** [comment]
Aggiunta la riga, ma fallisce
[npm-debug.zip](https://github.com/italia-it/ita-web-toolkit/files/655093/npm-debug.zip)

Mentre il comando pare dia lo stesso output
> C:\Users\Seba\git\ita-web-toolkit>node node_modules\suitcss-preprocessor\bin\suitcss -m -c .postcss.js index.css build\b
> uild.css
> C:\Users\Seba\git\ita-web-toolkit\config.js:1
> (function (exports, require, module, __filename, __dirname) { let CONFIG = {}
>                                                               ^^^
> 
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (C:\Users\Seba\git\ita-web-toolkit\.postcss.js:4:16)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)

**Comment by gunzip** [comment]
prova con  'use strict' anche all'inizio del file `config.js`

**Comment by sebailfico** [comment]
> ? Build started...
> ? Exported 442 of 442 items
> ? Build finished with no errors.

:+1:

**Comment by gunzip** [comment]
grazie, ho integrato i necessari aggiustamenti per la prossima release.
