### ISSUE TITLE
After build, file mancanti

### ISSUE THREAD

**Issue by sebailfico** [italia-it/ita-web-toolkit#35]
Rieccomi, dopo la build ho lanciato l'index.html dentro la cartella styleguide (già che ho apache installato l'ho usato) ma andando agli esempi sotto `http://localhost/styleguide/components/detail/page--default.html` mi lancia un 404 per i seguenti files:
> layout--default.html:229 GET http://localhost/styleguide/build/IWT.js 
> layout--default.html:41 GET http://localhost/styleguide/build/suitcss-base 
> layout--default.html:41 GET http://localhost/styleguide/build/suitcss-components 
> layout--default.html:41 GET http://localhost/styleguide/build/suitcss-utils 
> layout--default.html:229 GET http://localhost/styleguide/build/IWT.js 

Qui sotto lo snap del contenuto della cartella styleguide
![cattura](https://cloud.githubusercontent.com/assets/3844289/21244476/1d7da294-c31e-11e6-8593-e41eb3b4dee9.PNG)

Al di là del riuscire a lanciare gli esempi, ciò che mi interessa davvero è sapere dove trovo i files strettamente necessari per lavorarci, senza trascinarmi dietro esempi o duplicati, cosa che mi pare non ci sia nella documentazione.

Grazie ancora.

**Comment by gunzip** [comment]
per avviare il server con la styleguide (per visualizzare gli esempi quindi) è necessario utilizzare `npm run watch` e connettersi a http://localhost:1310.

se vuoi invece utilizzare i JS / CSS compilati in un tuo progetto (tramite apache o qualsiasi altro server) devi aver cura di linkare quelli che vedi all'interno della directory di cui riporti lo screenshot all'interno di un tuo index.

un index generico ha questa forma: https://github.com/italia-it/ita-web-toolkit/blob/master/src/_preview.tmpl (sostituendo opportunamente i percorsi).

i file strettamente necessari per lavorarci sono quindi `build.css`, `IWT.min.js`, `vendor.css` più i polyfill contenuti nella dir `vendor` per IE8 / IE9 . il percorso corretto dipende dalla configurazione del tuo server / vhost.

**Comment by sebailfico** [comment]
Purtroppo genera errori anche se hostato da node, avevo già provato ma come sempre dimentico di dirlo :-D

> page--default:41 GET http://localhost:1310/build/suitcss-base 
> page--default:41 GET http://localhost:1310/build/suitcss-components 
> page--default:41 GET http://localhost:1310/build/suitcss-utils 

Grazie per le dritte sui file da impiegare, domani in ogni caso do fuoco alla cartella e riparto da un git clone fresco e rifaccio tutti gli step, poi aggiorno l'issue.

**Comment by sebailfico** [comment]
Ho eseguito di nuovo tutti gli step, questa volta senza errori ( dopo aver aggiunto lo 'use strict' al config.js, ma continua a non trovare i file
> page--default:41 GET http://localhost:1310/build/suitcss-base 
> page--default:41 GET http://localhost:1310/build/suitcss-components 
> page--default:41 GET http://localhost:1310/build/suitcss-utils 

Che non sono presenti nella cartella build

**Comment by gunzip** [comment]
ho aggiornato il package.json con le dipendenze mancanti.

puoi riprovare adesso dopo `git pull` `npm install`

**Comment by sebailfico** [comment]
Pare che ora ci sia tutto!

Grazie
